import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SectionNav from "@/components/SectionNav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fantasia!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <main style={{ minHeight: "100vh", padding: "2rem", display: "flex", flexDirection: "column", gap: "1.5rem" }}>
          <h1 style={{ margin: 0 }}>Fantasia — Isometric 3D Engine</h1>
          <SectionNav />
          {children}
        </main>
      </body>
    </html>
  );
}
